import type {Metadata} from "next";


export const metadata: Metadata = {
	title: 'components',
	description: 'Generated by create next app',
};


export default function ComponentsPageLayout({children}: {
	children: React.ReactNode
}) {
	return (<html lang="en">
	<body>{children}</body>
	</html>)
}